## NumPy

NumPy is the fundamental package for scientific computing with Python. It contains among other things:

- a powerful N-dimensional array object
- sophisticated (broadcasting) functions
- tools for integrating C/C++ and Fortran code
- useful linear algebra, Fourier transform, and random number capabilities

Besides it's obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

Documentation : [Numpy Documentation v1.17](https://www.numpy.org/doc/1.17/user/index.html)

### Let's import the library

```python
    import numpy as np
```

In [ ]:
import numpy as np

### NumPy ndarray: A Multidimensional Array Object

One of the key features of NumPy is its N-dimensional array object, or ndarray, which is a fast, flexible container for large data sets in Python. Arrays enable you to perform mathematical operations on whole blocks of data using similar syntax to the equivalentoperations between scalar elements

```python
    data = [0.567, 0.123123, 0.234, 0.7823, 0.9812]
    ndarray = np.array(data)
    ndarray
```

Tasks: Create a sensor readings ndarray with the values of [0.167, 0.589, 0.225, 0.971]

In [ ]:
# Please complete the following code

readings = [0.167, 0.589, 0.225, 0.971]
readings_array = np.array(2)
readings_array

array(2)

You are able to check on the dimension and data type with

```python
    # Dimension
    ndarray.shape
    
    # data type
    ndarray.dtype
```

Task: Complete the following code to check the shape and data type for the `readings_array`

In [ ]:
# Please complete the following code


print(readings_array)

2


### Creating Zeros Numpy Array

In addition to np.array, there are a number of other functions for creating new arrays. As examples, zeros and ones create arrays of 0’s or 1’s, respectively, with a given length or shape. empty creates an array without initializing its values to any particular value. To create a higher dimensional array with these methods, pass a tuple for the shape


```python

    # create 1 dimension with all zero
    np.zeros(10)
    
    # create a 2 dimension array
    np.zeros((2,2))
```
Try running the code

In [ ]:
# create 1 dimension with all zero
np.zeros(10)

# create a 2 dimension array
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

### Data Types for ndarrays

The *data type* or dtype is a special object containing the information the ndarray needs to interpret a chunk of memory as a particular type of data

```python
    
    number_list = [1,2,3]

    array_1 = np.array(number_list, dtype=np.float64)
    array_2 = np.array(number_list, dtype=np.int32)
```
Task: Replicate and run the code above

In [ ]:
number_list = [1,2,3]

array_1 = np.array(number_list, dtype=np.float64)
array_2 = np.array(number_list, dtype=np.int32)

### Basic  Indexing and Slicing

NumPy array indexing is a rich topic, as there are many ways you may want to select a subset of your data or individual elements. One dimensional arrays are simple; on the surface they act similarly to Python list.

Let's create a numpy array starts from 0 to 14
```python
    array_1 = np.arange(15)
    array_1
```

Selecting values from numpy array
```python
    array_1[4:8]
```
Task: Try to replicate and run the code above

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


### Universal Function: Fast Element-wise Array Functions

Up until this point, we can't really see the advantage of using a nparray, next we are going to see how we can use it to speed up our computation. A universal function, or ufunc, is a function that performs elementwise operations on data in ndarrays. You can think of them as fast vectorized wrappers for simple functions that take one or more scalar values and produce one or more scalar results.

```python
    array_1 = np.arange(12)
    
    # square root
    np.sqrt(array_1)
    
    # exponential
    np.exp(array_1)
```
Tasks: Replicate and run the code above

In [ ]:
array_1 = np.arange(12)
np.sqrt(array_1)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479])

### Mathematical and  Statistical Methods

The `nparray` also supports a set of mathematical functions which compute statistics about an entire array or about the data along an axis are accessible as array methods. These methods are useful during data analytics process. Aggregations (often called reductions) like sum, mean, and standard deviation std can either be used by calling the array instance method or using the top level NumPy function

```python
    array_1 = np.random.randn(4,4)
    array_1
    
    # mean
    array_1.mean()
    
    # sum
    array_1.sum()
    
    #cumulative sum
    array_1.cumsum()
    
    # Cumulative Product
    array_2.cumprod()
```